### ISSUE TITLE
Missing gallery plots for v1.8.0rc1

### ISSUE THREAD

**Issue by ajdawson** [SciTools/scitools.org.uk#106]
The [gallery](http://scitools.org.uk/iris/docs/dev/gallery.html) has an incorrect image for the [Colouring anomaly data with logarithmic scaling](http://scitools.org.uk/iris/docs/dev/examples/General/anomaly_log_colouring.html#anomaly-log-colouring) example, and a missing/broken image for [Example of a polar stereographic plot](http://scitools.org.uk/iris/docs/dev/examples/General/polar_stereo.html#polar-stereo).

**Comment by marqh** [comment]
the anomoly plot is being cause dby this issue:
https://github.com/SciTools/cartopy/issues/597
which I'm investigating

i've not got a root cause on the stereo yet
mark

**Comment by marqh** [comment]
these are fixed on the latest version, uploaded for 1.8.0:
http://scitools.org.uk/iris/docs/latest/examples/General/anomaly_log_colouring.html#anomaly-log-colouring
http://scitools.org.uk/iris/docs/latest/examples/General/polar_stereo.html#polar-stereo
