### ISSUE TITLE
Pending CLAs

### ISSUE THREAD

**Issue by ajdawson** [SciTools/scitools.org.uk#140]
There are a number of PRs pending a CLA before they can be merged. Can someone at the MO confirm receipt/acceptance of CLAs from:

@dopplershift
@jsignell
@MartinDix

**Comment by ajdawson** [comment]
Any chance you can handle this @marqh - each has a completed PR that is waiting for merge.

**Comment by QuLogic** [comment]
Ping. CLAs do no good if they hold up development.

**Comment by pp-mo** [comment]
Thanks for the nudge @QuLogic 
Unfortunately, I think the emails are probably with @marqh, who is currently off sick ...
We will action as soon as he is back

**Comment by marqh** [comment]
despite reports to teh contrary my health is fine, unlike my github and CLA notifications which are experiencing a high noise to signal ratio; apologies for missing these

I have no processed these 3 CLAs (plus two more) and added gtihub IDs to a new PR: #144

**Comment by QuLogic** [comment]
Thanks @marqh! I don't see @MartinDix in there though?

**Comment by marqh** [comment]
> Thanks @marqh! I don't see @MartinDix in there though?

I'm afraid I don't have a CLA for @MartinDix

**Comment by QuLogic** [comment]
I'm not sure where his PR is; @ajdawson?

**Comment by ajdawson** [comment]
SciTools/iris#2080 but no confirmation a CLA was actually submitted.
