### ISSUE TITLE
Add a link to this github website repo from the website?

### ISSUE THREAD

**Issue by jypeter** [SciTools/scitools.org.uk#159]
You may want to add an explicit  link to the website related issues from http://scitools.org.uk/cartopy/docs/latest/index.html#getting-involved, possibly in _Contribute to the documentation_

**Comment by ajdawson** [comment]
It is fairly rare that contributors need to modify this repository. The cartopy documentation, including the page you linked is contained in the [cartopy repository](https://github.com/SciTools/cartopy/tree/master/docs). Can you explain more clearly what you are suggesting is added?

**Comment by jypeter** [comment]
It's just that I was looking for a place to report https://github.com/SciTools/cartopy/issues/917 and I did not know which _issue_ to use. Not knowing where the documentation was hosted, I looked in https://github.com/SciTools and I found this repo that has the following summary: _The contents of the www.scitools.org.uk website_

So, the documentation could mention that Cartopy documentation related issues can also go to https://github.com/SciTools/cartopy/issues

**Comment by ajdawson** [comment]
Adding a note to the *Cartopy* documentation is a good idea, thanks for the suggestion. For reference, *The contents of the www.scitools.org.uk website* refers to the content of the root directory served by the webserver.

The iris and cartopy documentation here is already processed and built and cannot be modified directly. However, this is the right place to come if you want to modify the scitools.org.uk website itself (e.g. the homepage, contributors list etc.).

**Comment by ajdawson** [comment]
I'm going to close this and move over to scitools/cartopy#918.

**Comment by jypeter** [comment]
OK, makes sense
