### ISSUE TITLE
Issues with new site design

### ISSUE THREAD

**Issue by ajdawson** [SciTools/scitools.org.uk#195]
The menu button (3-bars that replace right hand side navbar items) that appears in the mobile view doesn't do anything when you click on it. It should display a menu pop-up with the navbar options (Home, Organisation, Documentation, Github). You can reproduce in Chrome by navigating to https://scitools.org.uk and using the developer tools to simulate Pixel 2 (although any mobile setting I tried including iPad shows the same issue).

There is also a warning in the console: `Failed to load resource: net::ERR_NAME_NOT_RESOLVED count.json:1`. I don't know what this relates to or if it is important.

**Comment by pelson** [comment]
Thanks @ajdawson. Will take a look.
