### ISSUE TITLE
Reinstate the contributors list

### ISSUE THREAD

**Issue by ajdawson** [SciTools/scitools.org.uk#205]
I'd like to see the rendered list of contributors return to the scitools website. The README states that:

> `contributors.json` contains a JSON dictionary of all contributors who have signed the scitools CLA. It is the definitive source (as rendered in scitools.org.uk/about.html)

This is no longer true, in that the about page is different and does not contain the rendered list of contributors.

This page was useful when a human wants to check why the CLA bot failed (sometimes the submitting user has signed the CLA but the commit isn't using a registered email) and provide feedback to users submitting PRs.

**Comment by pelson** [comment]
Sounds like even a link to contributors.json would be useful?
Definitely support having a link. Rendering the full contributors list I'm not 100% on yet.

**Comment by ajdawson** [comment]
It doesn't have to be fancy or even linked, but it would be nice not to have to read json to work out if a contributor already signed the CLA and just needs to add an email alias to Github. Just a simple table that eliminates the punctuation overload that you see when reading json would do.
