### ISSUE TITLE
Documentation for 2.2.1 shows error 404

### ISSUE THREAD

**Issue by ajdawson** [SciTools/scitools.org.uk#224]
It looks like there is a spurious html directory inside the iris 2.2.1 docs directory merged in #223, the content from that directory should be moved into the 2.2.1 directory (iris/docs/v2.2.1/html/* -> iris/docs/v2.2.1/)

**Comment by lbdreyer** [comment]
Thanks @ajdawson I have reverted #223 so that https://scitools.org.uk/iris/docs/latest/ is back.

I will try to put up a new PR with the right directory structure

**Comment by lbdreyer** [comment]
This was fixed in #226
