### ISSUE TITLE
Change the "Click here to download the full example code" at the top of the cartopy Gallery examples?

### ISSUE THREAD

**Issue by jypeter** [SciTools/scitools.org.uk#252]
When I click on some (all?) examples of the [Cartopy Gallery](https://scitools.org.uk/cartopy/docs/latest/gallery/index.html), e.g. the [Global Map](https://scitools.org.uk/cartopy/docs/latest/gallery/lines_and_polygons/global_map.html) example, there is the following text at the top of the page

```
Note
Click HERE to download the full example code
```
I naively expect that clicking [HERE](https://scitools.org.uk/cartopy/docs/latest/gallery/lines_and_polygons/global_map.html#sphx-glr-download-gallery-lines-and-polygons-global-map-py) will point to a `.py` script and that a popup will open asking me where I want to save it.

But all it does is just scroll down to the bottom of the page where the script is displayed, which I can find by just scrolling down the page!!

Is there a way to get the actual download behavior I'm expecting? Otherwise you can probably just remove the Note :-)

**Comment by rcomer** [comment]
This note comes from `sphinx-gallery`, and they recently updated it so the link reads "Go to the end" - https://github.com/sphinx-gallery/sphinx-gallery/pull/1040.  So I guess that will filter through to Cartopy next time the docs are built.
