### ISSUE TITLE
Purge redundant website content

### ISSUE THREAD

**Issue by pp-mo** [SciTools/scitools.org.uk#60]
The website is currently updated by adding bits (i.e. uploading stuff), 
 - but this can leave obsolete stuff in place.

Have now removed all references to the obsolete /pages/ htmls
  - see https://github.com/SciTools/scitools.org.uk/pull/61

But ideally, we do also need to purge out all the obsolete info.

Key aim : **make the scitools website a simple image of the repo.**

**Comment by pelson** [comment]
the repo is now the content. :tada: :balloon:
